name: 'ghdl'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'
  repository_dispatch:
    types: [ ghdl ]

jobs:

  ghdl:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: TODO test hdlc/pkg:ghdl
      run: docker run --rm -v $(pwd):/wrk alpine /wrk/test/todo.sh
      #uses: docker://alpine
      #with:
      #  args: ./test/todo.sh

    - run: docker run --rm -v $(pwd):/wrk hdlc/ghdl /wrk/test/ghdl.sh
      #uses: docker://hdlc/ghdl
      #with:
      #  args: ./test/ghdl.sh
