name: 'impl'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'
  repository_dispatch:
    types: [ impl ]

jobs:

  impl:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build images
      run: |
        docker build -t hdlc/impl:ice40 --target=ice40 - < impl.dockerfile
        docker build -t hdlc/impl:ecp5 --target=ecp5 - < impl.dockerfile

    - run: docker run --rm -v $(pwd):/wrk hdlc/impl:ecp5 /wrk/test/impl--ecp5.sh
      #uses: docker://hdlc/impl
      #with:
      #  args: ./test/impl.sh

    - run: docker run --rm -v $(pwd):/wrk hdlc/impl:ice40 /wrk/test/impl--ice40.sh
      #uses: docker://hdlc/impl
      #with:
      #  args: ./test/impl.sh

    - name: Deploy to DockerHub
      run: |
        docker push hdlc/impl:ice40
        docker push hdlc/impl:ecp5
