name: 'impl'

on:
  push:
  repository_dispatch:
    types: [ impl ]

jobs:

  impl:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build images
      run: |
        docker build -t se0bi/hdlc-impl:ice40      --target=ice40      - < impl.dockerfile
        docker build -t se0bi/hdlc-impl:ecp5       --target=ecp5       - < impl.dockerfile
        docker build -t se0bi/hdlc-impl:pnr        --target=pnr        - < impl.dockerfile
        docker build -t se0bi/hdlc-impl:icestorm   --target=icestorm   - < impl.dockerfile
        docker build -t se0bi/hdlc-impl:prjtrellis --target=prjtrellis - < impl.dockerfile
        docker build -t se0bi/hdlc-impl:latest     --target=latest     - < impl.dockerfile

    - run: docker run --rm -v $(pwd):/wrk se0bi/hdlc-impl:ecp5 /wrk/test/impl--ecp5.sh
      #uses: docker://hdlc/impl:ecp5
      #with:
      #  args: ./test/impl--ecp5.sh

    - run: docker run --rm -v $(pwd):/wrk se0bi/hdlc-impl:ice40 /wrk/test/impl--ice40.sh
      #uses: docker://hdlc/impl:ice40
      #with:
      #  args: ./test/impl--ice40.sh

    - name: Deploy to DockerHub
      run: |
        docker push se0bi/hdlc-impl:ice40
        docker push se0bi/hdlc-impl:ecp5
        docker push se0bi/hdlc-impl:pnr
        docker push se0bi/hdlc-impl:icestorm
        docker push se0bi/hdlc-impl:prjtrellis
        docker push se0bi/hdlc-impl:latest
