name: 'nextpnr'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'
  repository_dispatch:
    types: [ nextpnr ]

jobs:

  nextpnr:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build images
      run: |
        docker build -t hdlc/pkg:nextpnr-ice40 --target=pkg-ice40 - < nextpnr.dockerfile
        docker build -t hdlc/pkg:nextpnr-ecp5 --target=pkg-ecp5 - < nextpnr.dockerfile
        docker build -t hdlc/nextpnr:ice40 --target=ice40 - < nextpnr.dockerfile
        docker build -t hdlc/nextpnr:ecp5 --target=ecp5 - < nextpnr.dockerfile
        docker build -t hdlc/nextpnr - < nextpnr.dockerfile

    - run: docker run --rm -v $(pwd):/wrk hdlc/nextpnr:ice40 /wrk/test/nextpnr--ice40.sh
      #uses: docker://hdlc/nextpnr:ice40
      #with:
      #  args: ./test/nextpnr-ice40.sh

    - run: docker run --rm -v $(pwd):/wrk hdlc/nextpnr:ecp5 /wrk/test/nextpnr--ecp5.sh
      #uses: docker://hdlc/nextpnr:ecp5
      #with:
      #  args: ./test/nextpnr-ecp5.sh

    - run: docker run --rm -v $(pwd):/wrk hdlc/nextpnr /wrk/test/nextpnr.sh
      #uses: docker://hdlc/nextpnr
      #with:
      #  args: ./test/nextpnr.sh

    - name: Deploy to DockerHub
      run: |
        docker push hdlc/pkg:nextpnr-ice40
        docker push hdlc/pkg:nextpnr-ecp5
        docker push hdlc/nextpnr:ice40
        docker push hdlc/nextpnr:ecp5
        docker push hdlc/nextpnr
