name: 'prjtrellis'

on:
  push:
  repository_dispatch:
    types: [ prjtrellis ]

jobs:

  prjtrellis:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build images
      run: |
        docker build -t se0bi/hdlc-pkg:prjtrellis --target=pkg - < prjtrellis.dockerfile
        docker build -t se0bi/hdlc-prjtrellis - < prjtrellis.dockerfile

    - name: TODO test se0bi/hdlc-pkg:prjtrellis
      run: docker run --rm -v $(pwd):/wrk alpine /wrk/test/todo.sh
      #uses: docker://alpine
      #with:
      #  args: ./test/todo.sh

    - run: docker run --rm -v $(pwd):/wrk se0bi/hdlc-prjtrellis /wrk/test/prjtrellis.sh
      #uses: docker://se0bi/hdlc-prjtrellis
      #with:
      #  args: ./test/prjtrellis.sh

    - name: Deploy to DockerHub
      run: |
        docker push se0bi/hdlc-pkg:prjtrellis
        docker push se0bi/hdlc-prjtrellis
