name: 'prog'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'
  repository_dispatch:
    types: [ prog ]

jobs:

  prog:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: docker run --rm -v $(pwd):/wrk hdlc/prog /wrk/test/prog.sh
      #uses: docker://hdlc/prog
      #with:
      #  args: ./test/prog.sh
