name: 'symbiyosys'

on:
  push:
  repository_dispatch:
    types: [ symbiyosys ]

jobs:

  symbiyosys:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: TODO test hdlc/pkg:symbiyosys
      run: docker run --rm -v $(pwd):/wrk alpine /wrk/test/todo.sh
      #uses: docker://alpine
      #with:
      #  args: ./test/todo.sh
