name: 'yosys'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'
  repository_dispatch:
    types: [ yosys ]

jobs:

  yosys:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build images
      run: |
        docker build -t se0bi/hdlc-pkg:yosys --target=pkg - < yosys.dockerfile
        docker build -t se0bi/hdlc-yosys - < yosys.dockerfile

    - name: TODO test se0bi/hdlc-pkg:yosys
      run: docker run --rm -v $(pwd):/wrk alpine /wrk/test/todo.sh
      #uses: docker://alpine
      #with:
      #  args: ./test/todo.sh

    - run: docker run --rm -v $(pwd):/wrk se0bi/hdlc-yosys /wrk/test/yosys.sh
      #uses: docker://se0bi/hdlc-yosys
      #with:
      #  args: ./test/yosys.sh

    - name: Deploy to DockerHub
      run: |
        docker push se0bi/hdlc-pkg:yosys
        docker push se0bi/hdlc-yosys
